default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_app_development
  username: postgres
  password: div@var8
  host: localhost
  port: 5432

test:
  <<: *default
  database: blog_app _test
  username: postgres
  password: div@var8
  host: localhost
  port: 5432

production:
  <<: *default
  database: blog_app_production
  username: blog_app
  password: <%= ENV["BLOG_APP_DATABASE_PASSWORD"] %>
